--- 
  - name: Setting ntp
    template:
      src: ntp.conf.j2
      dest: '/etc/ntp.conf'
      owner: root
      group: root
      backup: yes

  - name: sync time
    raw: net time set {{ ad_server }}

  - name: Restart ntp
    service:
      name: ntp
      state: restarted
